message: Missing or errors exist in line two of the `Copyright` section.
extends: occurrence
scope: raw
level: error
link: 'https://openid.net/documentation/rules/require_title.html'
min: 1
ignorecase: false
token: "The OpenID Foundation [(]OIDF[)] grants to any Contributor, developer, implementer, or other interested party a non-exclusive, royalty free, worldwide copyright license to reproduce, prepare derivative works from, distribute, perform and display, this Implementers Draft or Final Specification solely for the purposes of [(]i[)] developing specifications, and [(]ii[)] implementing Implementers Drafts and Final Specifications based on such documents, provided that attribution be made to the OIDF as the source of the material, but that such attribution does not indicate an endorsement by the OIDF[.]"
