name: OID4VCI document push
on:
  pull_request_review:
    types: 
    - submitted

jobs:
    demo-job:
        name: Placeholder for deploy-and-merge script
        if: github.event.review.state == 'APPROVED'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Just Echo 
            run: |     
                echo "Placeholder for deploy-and-merge script!"
