name: Release checks 2
on:
  push:
    branches: 
    - 'release/**'
  workflow_dispatch:
    
jobs:
  Check:
    name: Run checks on proposed OIDF specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List Files
        run: |
          echo HTML files:
          find . -iname '*.html'
          echo
          echo MD files:
          find . -iname '[!READ]*.md'
          echo

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: considrd/openid-workflow
          path: main
          ssh-key: ${{ secrets.OPENID_WORKFLOW_DEPLOY_KEY }}
          
      - name: List Files
        run: |
          ls -l
          ls -l ./main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Unix 'tree' tool
        run: sudo apt-get install tree -y

      - name: Install Python requirements
        run: |
          cd ./main
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Output Python path
        id: python_path
        run: echo "::set-output name=path::$(which python)"

      - name: Get state of document
        run: |
          cd ./main
          python cli-tool.py -filename-state ../ekyc-ida/openid-connect-4-identity-assurance-1_0-final.html

  CreatePR:
    name: Placeholder for release checks script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Just echo
      run: |
        echo "hello world"
        ls
