name: Release checks
on:
  push:
    branches: 
    - 'release/**'
    
jobs:
  linting2:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.29.1/vale_2.29.1_Linux_64-bit.tar.gz -O vale.tar.gz
          tar -xvzf vale.tar.gz vale
          rm vale.tar.gz
      - name: Run Vale
        run: |
          ./vale --version
          ./vale ls-config
          ./vale --config=.github/vale/.vale.ini
  demo-job:
    name: Placeholder for release checks script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Just echo
      run: |
        echo "hello world"
        ls
