name: Release checks
on:
  push:
    branches: [ release/* ]

jobs:
    demo-job:
        name: Demo job
        runs-on: ubuntu-latest
        if: github.event.pull_request.base.ref == 'releases/**'
        steps:
            - uses: actions/checkout@v3
            - name: Just echo
              run: |     
                echo "Hello World!"