name: Release checks
on:
  push:
    branches: 
    - testrelease
    - 'release/**'
    
jobs:
    linting:
      name: runner / vale
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: errata-ai/vale-action@reviewdog
    demo-job:
        name: Placeholder for release checks script
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Just echo
              run: |     
                echo "Placeholder for release checks script!"
