name: OID4VCI document push
on:
  pull_request_review:
    types: 
    - submitted

jobs:
    demo-job:
        name: Demo job
        runs-on: ubuntu-latest
        if: github.event.pull_request.base.ref == 'release/**'
        steps:
          - uses: actions/checkout@v3
          - name: Just list files
            run: |     
                echo "Hello World!"
