name: Release checks
on:
  push:
    branches: 
    - 'release/**'
    
jobs:
  linting2:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v2.29.1/vale_2.29.1_Linux_64-bit.tar.gz -O vale.tar.gz
          tar -xvzf vale.tar.gz vale
          rm vale.tar.gz
      - name: List Files
        run: |
          echo HTML files:
          find . -iname '*.html'
          echo
          echo MD files:
          find . -iname '[!READ]*.md'
          echo
      - name: Run Vale
        run: |
          ./vale --version
          ./vale --config=.github/vale/.vale.ini ls-config
          ./vale . --config=.github/vale/.vale.ini --glob='[!README]*'
      - name: check for updated html file
        run: |
            echo "updated html check not implemented yet"
      - name: check file doesn't already exist
        run: |
            echo "check file doesn't already exist not implemented yet"
      - name: check recent publish date
        run: |
          date -R
          echo "check publish date not implemented yet"
      - name: check file naming standard conformance
        run: |
          echo "naming standard conformance check not implemented yet"
      - name: check file is an incremental version
        run: |
          echo "check file is an incremental version not implemented yet"
      - name: check embedded content is actually embedded
        run: |
          echo "check embedded content is embedded not implemented yet"
      - name: check references are latest and links are correct
        run: |
          echo "check references are latest and links are correct not implemented yet"
      
  demo-job:
    name: Placeholder for release checks script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Just echo
      run: |
        echo "hello world"
        ls
