name: Release checks
on:
  push:

jobs:
    demo-job:
        name: Demo job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Just echo
              run: |     
                echo "Hello World!"
