name: Release checks 2
on:
  push:
    branches: 
    - 'release/**'
  workflow_dispatch:
    
jobs:
  Check:
    name: Run checks on proposed OIDF specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: List Files
        run: |
          echo HTML files:
          find . -iname '*.html'
          echo
          echo MD files:
          find . -iname '[!READ]*.md'
          echo

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: considrd/openid-workflow
          path: openid-workflow
          ssh-key: ${{ secrets.OPENID_WORKFLOW_DEPLOY_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Unix 'tree' tool
        run: |
          sudo apt-get install tree -y
          tree

      - name: Install Python requirements
        run: |
          cd ./openid-workflow
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Output Python path
        id: python_path
        run: echo "::set-output name=path::$(which python)"

      - name: Run checks process
        run : |
          cd ./openid-workflow
          chmod +x ./process.sh
          ./process.sh