name: remote ssh command demo
on: [workflow_dispatch]

jobs:
  list_remote_ssh:
    name: list_remote_ssh
    runs-on: ubuntu-latest
    environment: openid.net/specs/
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.OIDF_SPECS_HOST }}
        username: ${{ secrets.OIDF_USERID }}
        key: ${{ secrets.OIDF_USERID_KEY }}
        port: ${{ secrets.OIDF_SPECS_PORT }}
        script: |
            whoami
            pwd
            ls
            ls /var/www/openid.net/htdocs/specs/